config/routes.rb
Rails.application.routes.draw do
  root 'home#default'
  
  get 'home/default'
  get 'home/about'
  get 'home/update'
  get 'home/contact_us'
  get 'home/iframe_example'
  get 'home/ajax_example'
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :allow_iframe_requests
  
  def default
  end

  def about
  end

  def update
  end

  def contact_us
  end
  
   
  def iframe_example
  end
   
  def ajax_example
  end
  
private

  def allow_iframe_requests
    # response.headers.delete('X-Frame-Options')
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
     
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "BB Client Questions"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_ajax_example.js.erb
<script type="text/javascript">
    ClientQuestionMonitorLibrary = {};
     
    (function (ClientQuestionMonitorLibrary) {
        
        var _ws = null;
         
        ClientQuestionMonitorLibrary.onMessage = function (data) {
            if ((/true/i).test(data.approved)){
                if ($("#question-cont-" + data.id).length == 0){
                    $('#questions-inner-cont').prepend("<div id='question-cont-" + data.id + "' class='panel panel-default'><div class='panel-heading'>" + data.name + " From " + data.from + "</div><div class='panel-body'>" + data.question + "</div></div>");
                        return $('#chat-text').stop().animate({
                        scrollTop: $('#chat-text')[0].scrollHeight
                    }, 800);
                }
            }
            else{
                if (data.id){
                    $("#question-cont-" + data.id).remove();
                }
            }
        };
        
        
         
        ClientQuestionMonitorLibrary.createWebsocket = function (parentCont) {
            var ws = Socket.createWebsocket();
        
            ws.onmessage = function(message) {
                var data;
                data = JSON.parse(message.data);
                
                ClientQuestionMonitorLibrary.onMessage(data);
            };
            
            _ws = ws;
           
            return ws;
        }
        
       
       
       
    }(ClientQuestionMonitorLibrary = ClientQuestionMonitorLibrary || {}));
    
    $( document ).ready(function() {
        alert(1);
        ClientQuestionMonitorLibrary.createWebsocket();
         alert(2);
    });

</script>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/ajax_example.html.erb
<h1>AJAX Example</h1>

<div class="container client-monitor">
  <div class="page-header">
    <h2>questions</h2>
  </div>
  
  <div id="questions-inner-cont">
    
  </div>
</div>

<%= render(:partial => 'ajax_example.js', :formats => [:js] ) %>

app/views/home/contact_us.html.erb
<h1>Home#contact_us</h1>
<p>Find me in app/views/home/contact_us.html.erb</p>

app/views/home/default.html.erb
<h1>BB Cleint Question Example</h1>

<br/>

<ul>
    <li><%= link_to 'iframe Example', home_iframe_example_path %></li>
    <li><%= link_to 'AJAX Example', home_ajax_example_path %></li>
</ul>

app/views/home/iframe_example.html.erb
<h1>iframe Example</h1>

<iframe width="100%" height="100%"  src="https://bb-questions-slavapa.c9users.io/he/questions/client_monitor"></iframe>

app/views/home/update.html.erb
<h1>Home#update</h1>
<p>Find me in app/views/home/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>